version: '3'

services:

    mysql:
      image: mysql:5.7.24
      environment:
        MYSQL_ROOT_PASSWORD: 3434gdfg345dfgdsg45g
        MYSQL_DATABASE: dog_classifier_app
      ports:
        - "3308:3306"
      volumes:
        - "./data:/var/lib/mysql:rw"


    web:
      build:
        context: ./web/
      ports:
        - "8000:8000"
      volumes:
        - "./data/images:/var/data:rw"
      links:
        - mysql
        - api

    api:
      build:
        context: ./api/
      ports:
        - "8001:8001"
#      volumes:
#        - "./data/images:/var/data:rw"

    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      links:
        - web
        - api
