version: '3'

services:


    web:
      build:
        context: ./web/
      ports:
        - "8000:8000"
      volumes:
        - "./data/images:/var/data:rw"



#      volumes:
#        - "./data/images:/var/data:rw"

    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      links:
        - web
