version: '3'

services:

    mysql:
      image: mysql:5.7.24
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: dog_classifier_app
      ports:
        - "3308:3306"
      volumes:
        - "./data:/var/lib/mysql:rw"


    dog_classifier_app:
      build:
        context: .
        dockerfile: Dockerfile_dog_classifier_app
      ports:
        - "5000:5000"
